name: Build Single Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    # First exclude problematic projects before any restore or clean operations
    - name: Update solution to exclude WixCustom and EQLogParserInstall projects
      run: |
        dotnet sln EQLogParser.sln remove WixCustom/WixCustom.csproj
        dotnet sln EQLogParser.sln remove EQLogParserInstall/EQLogParserInstall.wixproj
        
    # Exclude theme projects that have Syncfusion.Calculate.Base dependency issues
    - name: Update solution to exclude theme projects
      run: |
        dotnet sln EQLogParser.sln remove MaterialDarkCustom/Syncfusion.Themes.MaterialDarkCustom.csproj
        dotnet sln EQLogParser.sln remove MaterialLightCustom/Syncfusion.Themes.MaterialLightCustom.csproj
        
    # Update the EQLogParser.csproj to remove theme project references
    - name: Update main project file to remove theme dependencies
      run: |
        $projFile = "EQLogParser/EQLogParser.csproj"
        $content = Get-Content $projFile -Raw
        $content = $content -replace '<ProjectReference Include=".\\MaterialDarkCustom\\Syncfusion.Themes.MaterialDarkCustom.csproj" />', ''
        $content = $content -replace '<ProjectReference Include=".\\MaterialLightCustom\\Syncfusion.Themes.MaterialLightCustom.csproj" />', ''
        Set-Content $projFile $content
        
    - name: Clean Solution
      run: dotnet clean
      
    - name: Clear NuGet cache and restore dependencies
      run: |
        dotnet nuget locals all --clear
        dotnet restore
        
    - name: Build Single Executable
      run: |
        dotnet publish EQLogParser/EQLogParser.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:DebugType=None /p:DebugSymbols=false /p:EnableCompressionInSingleFile=true /p:IncludeAllContentForSelfExtract=true -o publish
        
    - name: Rename executable
      run: |
        cd publish
        if (Test-Path "EQLogParser.exe") {
          Rename-Item -Path "EQLogParser.exe" -NewName "THJLogParser.exe"
        }
        
    - name: Copy data files
      run: |
        if (Test-Path "EQLogParser/data") {
          Copy-Item -Path "EQLogParser/data" -Destination "publish/data" -Recurse -Force
        }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: THJLogParser
        path: publish/ 